name: "Setup JFrog CLI Example"
on: push
permissions:
  contents: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4   # This must be indented correctly under the step
        env:
          JF_URL: "https://idani.jfrog.io"
          JF_PROJECT: "dk-a"   # This must be under `env` as well
        with:
          oidc-provider-name: davidka2
      
      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          # Collect environment variables for the build
          jf audit
