name: "Setup JFrog CLI Example"
on: push
permissions:
  contents: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4   # This must be indented correctly under the step
        env:
          JF_URL: "https://gpgtest.jfrog.io"
          #JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
        with:
          oidc-provider-name: davidka
          version: 2.76.1
      
      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          # Collect environment variables for the build
          jf audit
